-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: ['--autofix', '--indent=2', '--top-keys=name,version,description']
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v4.4.1
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint-config-google@0.9.1
        -   eslint-loader@1.9.0
        -   eslint-plugin-react@7.3.0
        -   babel-eslint@7.2.3
